# Generated by Django 5.1.1 on 2024-09-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scannedqr_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedqr',
            name='event_day',
            field=models.CharField(default='12', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scannedqr',
            name='event_name',
            field=models.CharField(default='13', max_length=100),
            preserve_default=False,
        ),
    ]
